# Generated by Django 5.2.18 on 2026-10-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(upload_to='images/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumb',
            field=models.FileField(blank=True, upload_to='images/thumbs/%Y/%m/'),
        ),
    ]
