# Generated by Django 5.2.17 on 2026-10-06 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, help_text='A short code of our own, e.g. "MOU".', max_length=30)),
                ('kind', models.CharField(choices=[('distributor', 'Distributor'), ('manufacturer', 'Manufacturer'), ('service', 'Service provider'), ('other', 'Other')], default='distributor', max_length=20, verbose_name='Type')),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, help_text='The general or sales address.', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Address')),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, help_text='Our customer number with them.', max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='VAT / tax ID')),
                ('payment_terms', models.CharField(blank=True, help_text='e.g. "30 days net".', max_length=100)),
                ('currency', models.CharField(blank=True, help_text='e.g. EUR, USD.', max_length=3)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, help_text='How long they usually take to deliver.', null=True, verbose_name='Lead time (days)')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Untick when we no longer buy from them.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, help_text='e.g. Sales, Support, Accounts.', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='vendors.vendor')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
