"""
Django settings for osmia project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from osmia import addons, settings_paths

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Everything Osmia stores: the database, uploaded images, installed modules and
# backups. On a server, this is the one folder to keep (and back up).
DATA_DIR = settings_paths.data_dir()


# Development defaults; set these environment variables for a real deployment.
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('OSMIA_DEBUG', '1') == '1'

# SECURITY WARNING: keep the secret key used in production secret!
# The fallback is public (it's in the repository), so it is only allowed with DEBUG on.
SECRET_KEY = os.environ.get('OSMIA_SECRET_KEY', '')
if not SECRET_KEY:
    if not DEBUG:
        raise RuntimeError('Set the OSMIA_SECRET_KEY environment variable when OSMIA_DEBUG is off.')
    SECRET_KEY = 'django-insecure-local-development-only-do-not-deploy'

ALLOWED_HOSTS = [h for h in os.environ.get('OSMIA_ALLOWED_HOSTS', '').split(',') if h]

# Part lookup by part number (inventory/lookup.py). A free Mouser Search API key.
OSMIA_MOUSER_API_KEY = os.environ.get('OSMIA_MOUSER_API_KEY', '')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # The module framework: registry, hooks, shared layout.
    'core',
]

# Built in: always there. Users is the login, so it can't come and go.
INSTALLED_APPS += ['users']

# Osmia modules are installed from the website (Modules page, see osmia/addons.py)
# into DATA_DIR/addons/modules and listed in DATA_DIR/addons/installed.json.
#
# OSMIA_DEV_MODULES=all (or a comma list) runs the modules straight from the
# source in modules/ instead; `manage.py test` does that with all of them.
# OSMIA_SAFE_MODE=1 starts without any module, so a module that breaks
# startup can be switched off from the website (serve.py does this by itself).
ADDONS = addons.Store(DATA_DIR)
OSMIA_SAFE_MODE = os.environ.get('OSMIA_SAFE_MODE') == '1'
_dev = os.environ.get('OSMIA_DEV_MODULES', 'all' if sys.argv[1:2] == ['test'] else '')
if _dev:
    _bundled = addons.bundled_manifests()
    _wanted = set(_bundled) if _dev == 'all' else {m.strip() for m in _dev.split(',') if m.strip()}
    OSMIA_MODULES = [m for m in addons.dependency_order(_bundled) if m in _wanted]
    sys.path.insert(0, str(addons.BUNDLED_DIR))
    OSMIA_DEV = True
else:
    OSMIA_MODULES = [] if OSMIA_SAFE_MODE else ADDONS.enabled_labels()
    sys.path.insert(0, str(ADDONS.modules_dir))
    OSMIA_DEV = False

INSTALLED_APPS += OSMIA_MODULES

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # Change log: each request is one chain, acting as the module whose page it is.
    'core.audit.AuditMiddleware',
    # Until there's an administrator, every page goes to the setup page.
    'core.setup.SetupMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'osmia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.osmia',
            ],
        },
    },
]

WSGI_APPLICATION = 'osmia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DATA_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Uploads: images up to 20 MB each, module packages up to 50 MB.
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

# Uploaded images. They're served by Osmia itself, to logged-in users only
# (core.views.image_file), so no MEDIA_URL is needed.
MEDIA_ROOT = Path(os.environ.get('OSMIA_MEDIA_ROOT') or DATA_DIR / 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TEST_RUNNER = 'core.test_runner.OsmiaTestRunner'  # also finds the tests in modules/

AUTH_USER_MODEL = 'users.User'
LOGIN_URL = 'users:login'
LOGIN_REDIRECT_URL = 'core:home'
LOGOUT_REDIRECT_URL = 'users:login'
