# Generated by Django 5.2.17 on 2026-10-06 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['attribute__name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('default_value', models.CharField(blank=True, help_text='Example or typical value, shown as a hint on parts.', max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='inventory.category')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Untick to archive the part.', verbose_name='Active')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='inventory.category')),
                ('fits', models.ManyToManyField(blank=True, help_text='Parts used in or with this one: e.g. a D-sub housing accepts its crimp contacts.', related_name='fits_into', to='inventory.part', verbose_name='accepts')),
                ('mates_with', models.ManyToManyField(blank=True, help_text='Parts this one connects to, both ways: e.g. a 9-pin plug mates with a 9-socket receptacle.', to='inventory.part')),
            ],
            options={
                'ordering': ['part_number'],
            },
        ),
    ]
