# Generated by Django 5.2.17 on 2026-10-06 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='tools',
            field=models.ManyToManyField(blank=True, help_text='Tools to work with it, e.g. the crimp tool for a contact.', related_name='parts', to='tools.tool'),
        ),
        migrations.AddField(
            model_name='partattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_values', to='inventory.attribute'),
        ),
        migrations.AddField(
            model_name='partattributevalue',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='inventory.part'),
        ),
        migrations.AddConstraint(
            model_name='attribute',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='unique_attribute_per_category'),
        ),
        migrations.AddConstraint(
            model_name='partattributevalue',
            constraint=models.UniqueConstraint(fields=('part', 'attribute'), name='unique_value_per_part_attribute'),
        ),
    ]
