# Generated by Django 5.2.18 on 2026-10-07 07:10

import django.db.models.deletion
from django.db import migrations, models


def links_to_families(apps, schema_editor):
    """Each group of parts linked by the old "mates with" becomes a family.
    Their sides aren't known, so they're left for someone to set."""
    Part = apps.get_model('inventory', 'Part')
    MatingFamily = apps.get_model('inventory', 'MatingFamily')
    links = {}
    for part in Part.objects.prefetch_related('mates_with'):
        links[part.pk] = {p.pk for p in part.mates_with.all()}
    seen = set()
    for start, linked in links.items():
        if start in seen or not linked:
            continue
        group, todo = set(), [start]
        while todo:
            pk = todo.pop()
            if pk not in group:
                group.add(pk)
                todo.extend(links.get(pk, ()))
        seen |= group
        numbers = sorted(Part.objects.filter(pk__in=group).values_list('part_number', flat=True))
        name = ' / '.join(numbers)[:90]
        while MatingFamily.objects.filter(name=name).exists():
            name += '*'
        family = MatingFamily.objects.create(name=name, description='From the old "mates with" links: set each part\'s side.')
        Part.objects.filter(pk__in=group).update(mating_family=family)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatingFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'mating families',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='part',
            name='mating_side',
            field=models.CharField(blank=True, choices=[('pin', 'Pin'), ('socket', 'Socket')], help_text='Pin or socket: which side of the family this part is.', max_length=10, verbose_name='side'),
        ),
        migrations.AddField(
            model_name='part',
            name='mating_family',
            field=models.ForeignKey(blank=True, help_text='The connector family, e.g. D-sub DB25. It mates with the parts of the family on the other side.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='inventory.matingfamily'),
        ),
        migrations.RunPython(links_to_families, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='part',
            name='mates_with',
        ),
    ]
