# Generated by Django 5.2.17 on 2026-10-06 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, help_text="Short code, e.g. A or 1. A location's code joins the labels down the tree: rack row A, rack 1, shelf A is A1A.", max_length=20)),
                ('code', models.CharField(blank=True, db_index=True, editable=False, max_length=200)),
                ('path', models.CharField(blank=True, editable=False, max_length=500)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='stock.location')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, help_text='Flag as low stock at or below this quantity (all locations together).', max_digits=12)),
                ('average_cost', models.DecimalField(decimal_places=4, default=0, help_text='Average cost of what has been received, per unit.', max_digits=12)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory.part')),
            ],
            options={
                'verbose_name': 'part stock settings',
                'verbose_name_plural': 'part stock settings',
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='stock.location')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.part')),
            ],
            options={
                'ordering': ['part__part_number', 'location__path'],
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_type', models.CharField(choices=[('in', 'Receipt'), ('out', 'Issue'), ('adjust', 'Adjustment'), ('transfer', 'Transfer')], max_length=10, verbose_name='Type')),
                ('delta', models.DecimalField(decimal_places=2, help_text='Signed change to quantity on hand.', max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stock.location')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moves', to='stock.location')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moves', to='inventory.part')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
