# Generated by Django 5.2.17 on 2026-10-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designator', models.CharField(help_text='e.g. J01 (jack on the device) or P01 (plug).', max_length=20)),
                ('side', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='right', help_text='Where it sits in the harness designer.', max_length=5)),
                ('tag_columns', models.PositiveSmallIntegerField(default=1)),
                ('description', models.CharField(blank=True, help_text='What the connector is for, e.g. "Main power in".', max_length=200, verbose_name='Function')),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'designator'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('origin', models.CharField(choices=[('in_house', 'Made by us'), ('external', 'External')], default='in_house', max_length=20)),
                ('role', models.CharField(choices=[('product', 'Product (unit we build)'), ('test_equipment', 'Test equipment'), ('power_supply', 'Power supply'), ('electronic_load', 'Electronic / test load'), ('measurement', 'Measurement (DMM, scope, ...)'), ('signal_source', 'Signal generator / source'), ('interconnect', 'Interconnect (adapter, breakout, extension)'), ('other', 'Other')], default='product', max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('asset_tag', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(default='#3b7dd8', help_text='Colour of the device in the harness designer.', max_length=7)),
                ('notes', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('label', models.CharField(help_text='The number printed on the connector, e.g. 13.', max_length=20)),
                ('signal', models.CharField(blank=True, help_text='One of the signals in Devices > Signals.', max_length=50)),
                ('tag1', models.CharField(blank=True, max_length=50, verbose_name='Tag 1')),
                ('tag2', models.CharField(blank=True, max_length=50, verbose_name='Tag 2')),
                ('tag3', models.CharField(blank=True, max_length=50, verbose_name='Tag 3')),
                ('tag4', models.CharField(blank=True, max_length=50, verbose_name='Tag 4')),
                ('set_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Set')),
                ('set_type', models.CharField(blank=True, choices=[('straight', 'Straight'), ('twisted', 'Twisted'), ('shielded', 'Shielded'), ('twisted_shielded', 'Twisted shielded')], max_length=20)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='PinMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['from_pin__connector__position', 'from_pin__position'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TagOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.PositiveSmallIntegerField(choices=[(1, 'Tag 1'), (2, 'Tag 2'), (3, 'Tag 3'), (4, 'Tag 4')])),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['column', 'name'],
            },
        ),
    ]
