# Generated by Django 5.2.17 on 2026-10-06 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assemblies', '0002_initial'),
        ('devices', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connector',
            name='part',
            field=models.ForeignKey(blank=True, help_text='The connector part, e.g. a D-sub 25 socket. Its description is shown as the connector type in harnesses.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_connectors', to='inventory.part', verbose_name='Physical connector'),
        ),
        migrations.AddField(
            model_name='device',
            name='assembly',
            field=models.OneToOneField(blank=True, limit_choices_to={'assembly_type': 'device'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device', to='assemblies.assembly'),
        ),
    ]
