# Generated by Django 5.2.17 on 2026-10-06 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='responsible',
            field=models.ForeignKey(blank=True, help_text='Owner; verifies wiring to this device in harnesses.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connector',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='devices.device'),
        ),
        migrations.AddField(
            model_name='deviceversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deviceversion',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='devices.device'),
        ),
        migrations.AddField(
            model_name='pin',
            name='connector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='devices.connector'),
        ),
        migrations.AddField(
            model_name='pinmap',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_maps', to='devices.device'),
        ),
        migrations.AddField(
            model_name='pinmap',
            name='from_pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps_out', to='devices.pin'),
        ),
        migrations.AddField(
            model_name='pinmap',
            name='to_pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps_in', to='devices.pin'),
        ),
        migrations.AddField(
            model_name='tagoption',
            name='connector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_options', to='devices.connector'),
        ),
        migrations.AddConstraint(
            model_name='connector',
            constraint=models.UniqueConstraint(fields=('device', 'designator'), name='unique_connector_designator'),
        ),
        migrations.AddConstraint(
            model_name='deviceversion',
            constraint=models.UniqueConstraint(fields=('device', 'version'), name='unique_device_version'),
        ),
        migrations.AddConstraint(
            model_name='pin',
            constraint=models.UniqueConstraint(fields=('connector', 'position'), name='unique_pin_position'),
        ),
        migrations.AddConstraint(
            model_name='pinmap',
            constraint=models.UniqueConstraint(fields=('from_pin', 'to_pin'), name='unique_pin_map'),
        ),
        migrations.AddConstraint(
            model_name='tagoption',
            constraint=models.UniqueConstraint(fields=('connector', 'column', 'name'), name='unique_tag_option_per_connector'),
        ),
    ]
