# Generated by Django 5.2.18 on 2026-10-08 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_subtasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(choices=[('#3b82f6', 'Blue'), ('#16a34a', 'Green'), ('#ea580c', 'Orange'), ('#7c3aed', 'Purple'), ('#0d9488', 'Teal'), ('#db2777', 'Pink'), ('#ca8a04', 'Amber'), ('#475569', 'Slate')], default='#3b82f6', max_length=7)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Related tasks, e.g. Inventory. Changing it moves the subtasks too.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.taskgroup'),
        ),
    ]
