# Generated by Django 5.2.17 on 2026-10-06 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, max_length=50)),
                ('object_id', models.PositiveBigIntegerField(default=0)),
                ('object_label', models.CharField(max_length=200)),
                ('object_url', models.CharField(blank=True, max_length=300)),
                ('item_type', models.CharField(blank=True, max_length=100)),
                ('item_label', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(choices=[('created', 'Created'), ('changed', 'Changed'), ('deleted', 'Deleted')], max_length=10)),
                ('changes', models.JSONField(blank=True, default=list)),
                ('actor_module', models.CharField(blank=True, max_length=50)),
                ('chain_path', models.CharField(blank=True, max_length=200)),
                ('chain_id', models.CharField(blank=True, db_index=True, max_length=12)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'log entries',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
