# Generated by Django 5.2.17 on 2026-10-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('part_number', models.CharField(blank=True, help_text="The manufacturer's part / order number.", max_length=100)),
                ('kind', models.CharField(choices=[('crimp', 'Crimp tool'), ('insertion', 'Insertion / extraction tool'), ('stripper', 'Wire stripper'), ('cutter', 'Cutter'), ('soldering', 'Soldering'), ('measuring', 'Measuring / test'), ('hand', 'Hand tool'), ('other', 'Other')], default='other', max_length=20, verbose_name='Type')),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('asset_tag', models.CharField(blank=True, help_text='Our own number, if the tool is labelled.', max_length=100)),
                ('storage', models.CharField(blank=True, help_text='Where to find it, e.g. "Bench 2, drawer 3".', max_length=200, verbose_name='Kept at')),
                ('calibration_due', models.DateField(blank=True, help_text='For tools that need calibrating.', null=True)),
                ('notes', models.TextField(blank=True, help_text='e.g. which die or setting to use.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick when the tool is retired.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
