# Generated by Django 5.2.17 on 2026-10-06 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assemblies', '0002_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklink',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_link', to='tasks.task'),
        ),
        migrations.AddConstraint(
            model_name='assemblycomponent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('child_assembly__isnull', True), ('part__isnull', False)), models.Q(('child_assembly__isnull', False), ('part__isnull', True)), _connector='OR'), name='component_is_part_xor_assembly'),
        ),
        migrations.AddConstraint(
            model_name='assemblycomponent',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='component_quantity_positive'),
        ),
    ]
