# Generated by Django 5.2.17 on 2026-10-06 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budgets', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('received_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('placed', 'Placed'), ('partial', 'Partly received'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', editable=False, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('placed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('received_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='budgets.budget')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
